package:
  name: cassiopee_kcore
  version: "3.4"

source:
  path: ../src/KCore

build:
  number: 0

requirements:
  build:
   - python 3
   - scons
   - hdf5
   - numpy
   - cython
   - libpng
   - libgfortran
   - {{ compiler('c') }}
   - {{ compiler('fortran') }}
   - {{ compiler('cxx') }}

  run:
   - python 3
   - hdf5
   - numpy
   - libpng
   - mpi4py

test:
  requires:
    - numpy

  imports:
    - KCore

about:
  home: elsa.onera.fr/Cassiopee
  license: GPLv3
  summary: Core for *Cassiopee* modules.
