services:
  cassiopee:
    image: ${CASSIOPEE_IMAGE}
    container_name: cassiopee
    privileged: true
    stdin_open: true
    tty: true

    environment:
      DISPLAY: host.docker.internal:0

    volumes:
      - ${HOST_IO_PATH}:/io

