
package:
    name: cassiopee
    version: 3.4

source:
    - path: /stck/benoit/Cassiopee
      folder: Cassiopee

build:
    number: 1

requirements:
    build:
        - python 3
        - hdf5
        - numpy
        - libpng
        - scons
        - mpi4py
        - libgfortran
        - {{ compiler('c') }}
        - {{ compiler('fortran') }}
        - {{ compiler('cxx') }}
        
    run:
        - python 3
        - hdf5
        - numpy
        - libpng
        - mpi4py
    
    host:
        - python 3
   
